### ISSUE TITLE
Installed it manually. does not work.

### ISSUE THREAD

**Issue by tracure1337** [ARodenboog/embed-html#1]
Installed it manually. does not work.

**Comment by ARodenboog** [comment]
What issues are you having? I updated the README a bit to make it more understandable, I wrote this for myself initially so any feedback is greatly appreciated :)

**Comment by tracure1337** [comment]
Thanks for the swift reply & looking into it.

I copied it to my .obsidian/plugins folder and it appeared in my plugin list after a restart.
But when enabling it, it fails and says "failed to load obsidian-sample-plugin."

I tried installing that one as well but doesn't work.

**Comment by ARodenboog** [comment]
I could replicate your problem on a fresh pull, and updated the package to fix the issue.. The issue seems to be that Obsidian requires you to have prebuilt the typescript to javascript, which obsidian does automatically for listed community plugins, but not for manually copied plugins.
I just included the javascript build result, and it worked for me on a fresh pull in a fresh vault. Can you see if this solved it for you?

**Comment by tracure1337** [comment]
@ARodenboog Thanks so much! Works like a charm now.

Just having difficulties changing the link color from blue to white now..
Is there something in the embed overwriting the css set by a custom css?



```
a:-webkit-any-link {
  color: white;
}
```

doesn't seem to work.


![image](https://user-images.githubusercontent.com/43231640/192160334-287aa5d4-fb57-4b5d-abb8-c4ac728d5fe7.png)


My apology if that question is out of scope :-)

**Comment by tracure1337** [comment]
On another note: This is such a useful plugin. You should release it to the official list :-)

**Comment by tracure1337** [comment]
Fixed it. I tried to change it via obsidian css all the time...of course it's way simpler to fix the underlying .html. haha

Thanks!
